server:
  port: 8001
spring:
  application:
    name: spring-cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  output:
    ansi:
      enabled: always # 控制台彩色字体输出
#logging:
#  pattern:
#    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow}" #
# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml # 扫描mapper.xml
  type-aliases-package: com.lvbok.springcloud.entities # 所有entity别名类所在包
